title: 금융경제학
author: 박기영
copyright: "2026"

execute:
  execute_notebooks: off

repository:
  url: https://github.com/FinancialEconomicsPython/book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: https://financialeconomicspython.github.io/book/

sphinx:
  config:
    language: ko
