title: 금융경제학
author: 박기영

execute:
  execute_notebooks: off

repository:
  url: https://github.com/FinancialEconomicsPython/resources
  path_to_book: .    # 이 줄 추가!
  branch: main

html:
  use_repository_button: true

sphinx:
  config:
    language: ko
